const ADD_TASK = 'ADD_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const DELETE_TASK = 'DELETE_TASK';
const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
const OPEN_EDIT_TASK = 'OPEN_EDIT_TASK';
const CLOSE_EDIT_TASK = 'CLOSE_EDIT_TASK';

const REQUEST_TASKS = 'REQUEST_TASKS';
const RECEIVE_TASKS = 'RECEIVE_TASKS';
const RECEIVE_TASK = 'RECEIVE_TASK';

export default {
  ADD_TASK,
  UPDATE_TASK,
  DELETE_TASK,
  CHANGE_TASK_STATUS,
  OPEN_EDIT_TASK,
  CLOSE_EDIT_TASK,
  REQUEST_TASKS,
  RECEIVE_TASKS,
  RECEIVE_TASK,
};
