const ADD_TASK = 'ADD_TASK'
const EDIT_TASK = 'EDIT_TASK'
const COMPLETE_TASK = 'COMPLETE_TASK'
const DELETE_TASK = 'DELETE_TASK'

export default {
    ADD_TASK,
    EDIT_TASK,
    COMPLETE_TASK,
    DELETE_TASK,
}