const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
const OPEN_EDIT_TASK = 'OPEN_EDIT_TASK';
const CLOSE_EDIT_TASK = 'CLOSE_EDIT_TASK';

export default {
  DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
  DASHBOARD_SUCCESS: 'DASHBOARD_SUCCESS',
  DASHBOARD_FAILURE: 'DASHBOARD_FAILURE',

  TASK_DETAILS_REQUEST: 'TASK_DETAILS_REQUEST',
  TASK_DETAILS_SUCCESS: 'TASK_DETAILS_SUCCESS',
  TASK_DETAILS_FAILURE: 'TASK_DETAILS_FAILURE',

  CHANGE_TASK_STATUS,
  OPEN_EDIT_TASK,
  CLOSE_EDIT_TASK,
};
