const ADD_TASK = 'ADD_TASK';
const EDIT_TASK = 'EDIT_TASK';
const COMPLETE_TASK = 'COMPLETE_TASK';
const DELETE_TASK = 'DELETE_TASK';
const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
const GET_TASK_DETAIL = 'GET_TASK_DETAIL';

export default {
  ADD_TASK,
  EDIT_TASK,
  COMPLETE_TASK,
  DELETE_TASK,
  CHANGE_TASK_STATUS,
  LOAD_DASHBOARD,
  GET_TASK_DETAIL,
};
