const LOAD_PROFILE = 'LOAD_PROFILE';
const EDIT_PROFILE = 'EDIT_PROFILE';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';

export default {
  LOAD_PROFILE,
  EDIT_PROFILE,
  USER_LOGIN,
  USER_LOGOUT,
};
