const LOAD_PROFILE = 'LOAD_PROFILE';
const UDPATE_PROFILE = 'UDPATE_PROFILE';
const USER_LOGIN = 'USER_LOGIN';
const USER_LOGOUT = 'USER_LOGOUT';
const OPEN_EDIT_PROFILE = 'OPEN_EDIT_PROFILE';
const CLOSE_EDIT_PROFILE = 'CLOSE_EDIT_PROFILE';

export default {
  LOAD_PROFILE,
  UDPATE_PROFILE,
  USER_LOGIN,
  USER_LOGOUT,
  OPEN_EDIT_PROFILE,
  CLOSE_EDIT_PROFILE,
};
